### ISSUE TITLE
asahi-sources is masked per the ~amd64 keyword

### ISSUE THREAD

**Issue by NyaomiDEV** [chadmed/asahi-gentoosupport#19]
Installing Gentoo by using the linked guide, I was faced with emerge exiting at the installation of asahi-sources. This is because asahi-sources is marked as testing, for what I have read.

I agreed to all keywords just for that package for now, but probably this has to be accounted for in the install.sh script.

**Comment by chadmed** [comment]
We cannot stabilise `sys-kernel/asahi-sources` as it depends on unstable rust. The `install.sh` script now adds a file to `/etc/portage/package.accept_keywords/` to handle this. Hopefully this won't be required for long. We will push a Portage news item advising when it's safe to remove this.

**Comment by jannau** [comment]
asahi-sources-6.6.0_p16 is stable: https://packages.gentoo.org/packages/sys-kernel/asahi-sources
asahi-sources-6.8.6_p1 is unstable due to the new ebuild rules and due to be replaced by asahi-sources-6.8.6_p3 (those two also depend on unstable rust 1.76 or 1.77 but for now it's not what's holding the kernel back).
Those shall probably remain unstable due to issues discovered during the rollout on Fedora.
